apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-node-graceful
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-node-graceful
    spec:
      containers:
      - name: k8s-node-graceful
        image: brandondoran/k8s-node-graceful:1.3.4
        lifecycle:
          # This hook is called immediately before a container is terminated.
          # It is blocking, so must complete before the call to delete the container can be sent
          preStop:
            exec:
              # Sleep for 10 seconds to allow time for pod to be removed from load balancer
              command: ['/bin/sh', '-c', 'sleep 10 && echo $(date): preStop hook - Sleep expired >> /dev/termination-log']
        # Readiness Probe: determine if app is ready to serve requests.
        # Default state is "failure"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          # After an initial 5 second delay
          initialDelaySeconds: 5
          # Check readiness every 3 seconds
          periodSeconds: 3
          # The probe must respond within 1 second.
          timeoutSeconds: 1
          # If 2 probes fail, remove pod from service load balancer.
          failureThreshold: 2
          # After 1 success, add pod to service load balancer.
          successThreshold: 1
        ports:
        - containerPort: 3001
