apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-node-graceful
  name: k8s-node-graceful
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: k8s-node-graceful
  sessionAffinity: None
  type: NodePort
